### ISSUE TITLE
Trying to figure out how to strip 3 panel charts from Solo cms files in conversion

### ISSUE THREAD

**Issue by Wanny** [987123879113/gobbletools#1]
As you probably know from my babbling on 🐷.ws, I've been trying to properly convert the Solo 2000 .cms files but the 3 panel charts ruin everything... 

When converting a regular CMS file the output is the following (BA KKWO's file from 3rd KV2):
```
ddrcharttool.py -i bak8.cms -if cms -o all.sm -of sm
0 0 179
2 0 163
0 1 212
2 1 202
0 2 255
2 2 314
```

But with DDR Solo CMS files this happens (NONSTOP B from Solo 2000):
```
ddrcharttool.py -i mixb.cms -if cms -o mixb.sm -of sm
0 0 348
1 0 324
2 0 318
0 1 437
1 1 437
2 1 437
0 2 575
1 2 575
2 2 575
Traceback (most recent call last):
  File "E:\stuff\gobbletools-master\other\ddrcharttool.py", line 1721, in <module>
    data = reader.export_json()
  File "E:\stuff\gobbletools-master\other\ddrcharttool.py", line 1122, in export_json
    return CsqReader(self.data).export_json(filename)
  File "E:\stuff\gobbletools-master\other\ddrcharttool.py", line 378, in __init__
    self.chunks = self.parse()
  File "E:\stuff\gobbletools-master\other\ddrcharttool.py", line 542, in parse
    chunk['events'] = chunk_parsers.get(chunk['type'], lambda x: [])(chunk['_raw'])
  File "E:\stuff\gobbletools-master\other\ddrcharttool.py", line 665, in parse_note_events_chunk
    note_raw = event_extra_data[0]
IndexError: bytearray index out of range
```

What I noticed is that the IDs are messed up.

In a regular CMS:
- 0 is Single
- 2 is Double

In a Solo CMS:
- 0 is the 6 panel chart
- 1 is the 4 panel chart
- 2 is the 3 panel chart

Would it be possible to add an extra --solocms flag to ignore type 2 charts and properly rearrange the converted charts? 🤔

**Comment by 987123879113** [comment]
Fixed and seems like it works (based on Twitter comment) so closing this issue. Feel free to open another if you find another bug with this part of the code.
