### ISSUE TITLE
Question: How to actually use the Disney's Rave parse tool?

### ISSUE THREAD

**Issue by Wanny** [987123879113/gobbletools#19]
I know that the tools are released "as-is" and I tried my best to figure it myself but I'm stumped.

Upon just running the Disney's Rave parse tool I get a message asking for a disney_rave.exe file. I was like WTF?
Extracted the contents of the Disney's Rave GAME.DAT and there's no EXE inside so I assumed I had to rename DR's psx.exe to disney_rave,exe..

Then I ran the tool again on a directory containing the EXE, the extracted contents (the "0" and "1" folders) and this is the roadblock I'm at:

```
Traceback (most recent call last):
  File "F:\beemany tools\disneireib\parse_charts_disneysrave.py", line 239, in <module>
    title = read_string(data, title_ptr)
  File "F:\beemany toos\disneireib\parse_charts_disneysrave.py", line 11, in read_string
    string_bytes = data[offset:data.index(b'\0', offset)]
ValueError: subsection not found
```

I assume that \0 references the "0" folder?

Tried putting  both files INSIDE the folder and running the tool from there. Fail.
Tried putting the "0" folder at the root of the drive. Fail.

What should I do? I'm using Python 3.9.6

**Comment by 987123879113** [comment]
No, `b'\0'` means a null byte. Completely unrelated to folders.

You need to open the GAME.DAT and extract the PS-X EXE for the game (not the bootloader). Copy from 0x60000 until 0x11d000 and name that disney_rave.exe.

**Comment by Wanny** [comment]
Uh, seems I'm doing something wrong.

![image](https://github.com/987123879113/gobbletools/assets/569307/9ce08f25-5002-43e8-9484-741f0efebb38)

**Comment by 987123879113** [comment]
Nope. That looks right. What were you expecting to happen that isn't? 

If you read the code more you'd find you need to have all of the *.seq files in a folder named "charts" and the rest of the game data in a folder named "raw_data" if you're trying to convert the charts. You can just copy the raw_data folder twice and rename the second copy to charts.

The Disney's Rave and DCT tools are full on "provided as-is" tools that I expected people to read the code and figure it out if they wanted to use it, so you're going to get wonky stuff like that. They're there for the information the provide by reading the code, not to be made easily usable for everyone else.

**Comment by Wanny** [comment]
Now I understand the full extent of the "as is" part, haha. 
I'm not versed enough in Python to have noticed before the paths (they're mentioned in different parts of the code, that's my bad for not reading it enough)

(also, ran into the need for the MP3s in the "cd_data" folder 👀)

Finally made it to work, thanks a lot for your patience.

**Comment by 987123879113** [comment]
It's one of the more extreme examples admittedly. I usually put some effort into turning things into proper user usable tools, but there are a lot of tools that I make to run once but also required a lot of research (for this one it had the song database structure, the new chart format, etc) so I put those up still in case someone else can use it for whatever. This one I put no thought into the structure of the code and haven't looked at it in 2-3 years 

Since you got it working now I'm going to close this issue. Feel free to reopen or make a new one if needed.
