### ISSUE TITLE
A little error in ddrcharttool

### ISSUE THREAD

**Issue by Wanny** [987123879113/gobbletools#21]
The help says "input **folder**" and "output **folder**"...

![image](https://github.com/987123879113/gobbletools/assets/569307/bb219bd1-8c38-45af-8ac6-1b4171a01acf)

...when it's actually "input **file**" and "output **file**" respectively.

**Comment by 987123879113** [comment]
Thanks, fixed. https://github.com/987123879113/gobbletools/commit/64d590b5cec3a8e34ab0654e79262d852adfdb9c
