### ISSUE TITLE
Something's wrong with converting DDR A SSQ files

### ISSUE THREAD

**Issue by Wanny** [987123879113/gobbletools#3]
While gathering data to update an article about STARS (2nd Naoki's Style), I noticed that when converting DDR A/A20 SSQ files to SM the conversion is... wrong.

When converting the Party Collection SSQ everything looks fine:
![image](https://user-images.githubusercontent.com/569307/119870112-fd886380-beee-11eb-80e5-0d5d686cacfa.png)

But when converting the DDR A/A20 one this happens:
![image](https://user-images.githubusercontent.com/569307/119869943-d2057900-beee-11eb-944e-ae24e3b96a08.png)
For some reason all measures are squished together. Not to mention that the song only has 59 measures.... certainly not 127+

I tried the conversion with RhythmCodex and the resulting file is fine 🤔

**Comment by 987123879113** [comment]
The first tempo value was being handled incorrectly which resulted in a negative BPM at first. It's fixed now. https://github.com/987123879113/gobbletools/commit/138ffc2404f195e3e4425b62038a5ab556e6593e

![image](https://user-images.githubusercontent.com/63495610/124999808-eca04580-e089-11eb-96bc-80c79b40f506.png)
