### ISSUE TITLE
dump_sys573_gamefs ModuleNotFoundError: "No module named 'enc573'"

### ISSUE THREAD

**Issue by pm41224** [987123879113/gobbletools#4]
I tried to open the program mentioned in the title (via command line) and it spewed out the above error.

The error points to line 8 of dump_sys573_gamefs.py: "import enc573".

**Comment by 987123879113** [comment]
The detailed instructions were linked in the line here: For a better example of how to use these tools, check out https://github.com/987123879113/ddr5thmix-solo
but the exact solution isn't exactly clear even looking at that.

You need to execute this line before you can use enc573, comp573, etc: `python3 setup.py build_ext --inplace`

It'll take some additional configuration depending on your system to actually get it to build (if you're using Windows then you'll need to install the appropriate build tools for Visual Studio for example) but there are on screen prompts telling you what to install, and you should be able to find the rest of the Cython build instructions elsewhere online I think.

**Comment by 987123879113** [comment]
I updated the README to make it explicit: https://github.com/987123879113/gobbletools/commit/663153924e80a074d8bd4429140ff4f8bac3bf15

https://github.com/987123879113/gobbletools/blob/master/sys573/sys573tool/README.md
